server: 38.55.252.212:443
auth: Dashabi123@
tls:
  sni: 123.douyin112152.cn
  insecure: false
transport:
  udp:
    hopInterval: 30s
tcpForwarding:
  - listen: 127.0.0.1:8443
    remote: 127.0.0.1:8443
