listen: :443
tls:
  cert: /certs/fullchain.pem
  key: /certs/privkey.pem
auth:
  type: password
  password: Dashabi123@
masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true
bandwidth:
  up: 100 mbps
  down: 100 mbps
transport:
  udp:
    hopInterval: 30s
